# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0004_auto_20161218_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everydayspendinging',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_index.SpendingsBatch', verbose_name='Batch Name'),
        ),
    ]
